// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: piratas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Información del pirata ofrecido por el cazarrecompensas
type PirataCapturado struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre             string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Recompensa         int32                  `protobuf:"varint,3,opt,name=recompensa,proto3" json:"recompensa,omitempty"`
	CazarrecompensasId string                 `protobuf:"bytes,4,opt,name=cazarrecompensas_id,json=cazarrecompensasId,proto3" json:"cazarrecompensas_id,omitempty"`
	Peligrosidad       string                 `protobuf:"bytes,5,opt,name=peligrosidad,proto3" json:"peligrosidad,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PirataCapturado) Reset() {
	*x = PirataCapturado{}
	mi := &file_piratas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PirataCapturado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PirataCapturado) ProtoMessage() {}

func (x *PirataCapturado) ProtoReflect() protoreflect.Message {
	mi := &file_piratas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PirataCapturado.ProtoReflect.Descriptor instead.
func (*PirataCapturado) Descriptor() ([]byte, []int) {
	return file_piratas_proto_rawDescGZIP(), []int{0}
}

func (x *PirataCapturado) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PirataCapturado) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *PirataCapturado) GetRecompensa() int32 {
	if x != nil {
		return x.Recompensa
	}
	return 0
}

func (x *PirataCapturado) GetCazarrecompensasId() string {
	if x != nil {
		return x.CazarrecompensasId
	}
	return ""
}

func (x *PirataCapturado) GetPeligrosidad() string {
	if x != nil {
		return x.Peligrosidad
	}
	return ""
}

// Resultado de la compra
type ResultadoCompra struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Estado        string                 `protobuf:"bytes,2,opt,name=estado,proto3" json:"estado,omitempty"`
	Caso          string                 `protobuf:"bytes,3,opt,name=caso,proto3" json:"caso,omitempty"`
	MontoPagado   int32                  `protobuf:"varint,4,opt,name=monto_pagado,json=montoPagado,proto3" json:"monto_pagado,omitempty"` // Solo relevante si estado = EXITO
	Mensaje       string                 `protobuf:"bytes,5,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Entrega       string                 `protobuf:"bytes,6,opt,name=entrega,proto3" json:"entrega,omitempty"` // submundo o marina
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultadoCompra) Reset() {
	*x = ResultadoCompra{}
	mi := &file_piratas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoCompra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoCompra) ProtoMessage() {}

func (x *ResultadoCompra) ProtoReflect() protoreflect.Message {
	mi := &file_piratas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoCompra.ProtoReflect.Descriptor instead.
func (*ResultadoCompra) Descriptor() ([]byte, []int) {
	return file_piratas_proto_rawDescGZIP(), []int{1}
}

func (x *ResultadoCompra) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *ResultadoCompra) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *ResultadoCompra) GetCaso() string {
	if x != nil {
		return x.Caso
	}
	return ""
}

func (x *ResultadoCompra) GetMontoPagado() int32 {
	if x != nil {
		return x.MontoPagado
	}
	return 0
}

func (x *ResultadoCompra) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ResultadoCompra) GetEntrega() string {
	if x != nil {
		return x.Entrega
	}
	return ""
}

// Mensajes para el Gobierno
type SolicitudLista struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CazarrecompensaId string                 `protobuf:"bytes,1,opt,name=cazarrecompensa_id,json=cazarrecompensaId,proto3" json:"cazarrecompensa_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SolicitudLista) Reset() {
	*x = SolicitudLista{}
	mi := &file_piratas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudLista) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudLista) ProtoMessage() {}

func (x *SolicitudLista) ProtoReflect() protoreflect.Message {
	mi := &file_piratas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudLista.ProtoReflect.Descriptor instead.
func (*SolicitudLista) Descriptor() ([]byte, []int) {
	return file_piratas_proto_rawDescGZIP(), []int{2}
}

func (x *SolicitudLista) GetCazarrecompensaId() string {
	if x != nil {
		return x.CazarrecompensaId
	}
	return ""
}

type PirataInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Recompensa    uint64                 `protobuf:"varint,3,opt,name=recompensa,proto3" json:"recompensa,omitempty"`
	Peligrosidad  string                 `protobuf:"bytes,4,opt,name=peligrosidad,proto3" json:"peligrosidad,omitempty"`
	Estado        string                 `protobuf:"bytes,5,opt,name=estado,proto3" json:"estado,omitempty"` // "Buscado" o "Capturado"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PirataInfo) Reset() {
	*x = PirataInfo{}
	mi := &file_piratas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PirataInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PirataInfo) ProtoMessage() {}

func (x *PirataInfo) ProtoReflect() protoreflect.Message {
	mi := &file_piratas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PirataInfo.ProtoReflect.Descriptor instead.
func (*PirataInfo) Descriptor() ([]byte, []int) {
	return file_piratas_proto_rawDescGZIP(), []int{3}
}

func (x *PirataInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PirataInfo) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *PirataInfo) GetRecompensa() uint64 {
	if x != nil {
		return x.Recompensa
	}
	return 0
}

func (x *PirataInfo) GetPeligrosidad() string {
	if x != nil {
		return x.Peligrosidad
	}
	return ""
}

func (x *PirataInfo) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type ListaPiratas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piratas       []*PirataInfo          `protobuf:"bytes,1,rep,name=piratas,proto3" json:"piratas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaPiratas) Reset() {
	*x = ListaPiratas{}
	mi := &file_piratas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaPiratas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaPiratas) ProtoMessage() {}

func (x *ListaPiratas) ProtoReflect() protoreflect.Message {
	mi := &file_piratas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaPiratas.ProtoReflect.Descriptor instead.
func (*ListaPiratas) Descriptor() ([]byte, []int) {
	return file_piratas_proto_rawDescGZIP(), []int{4}
}

func (x *ListaPiratas) GetPiratas() []*PirataInfo {
	if x != nil {
		return x.Piratas
	}
	return nil
}

type ReporteCaptura struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CazarrecompensaId string                 `protobuf:"bytes,1,opt,name=cazarrecompensa_id,json=cazarrecompensaId,proto3" json:"cazarrecompensa_id,omitempty"`
	PirataId          string                 `protobuf:"bytes,2,opt,name=pirata_id,json=pirataId,proto3" json:"pirata_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReporteCaptura) Reset() {
	*x = ReporteCaptura{}
	mi := &file_piratas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReporteCaptura) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReporteCaptura) ProtoMessage() {}

func (x *ReporteCaptura) ProtoReflect() protoreflect.Message {
	mi := &file_piratas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReporteCaptura.ProtoReflect.Descriptor instead.
func (*ReporteCaptura) Descriptor() ([]byte, []int) {
	return file_piratas_proto_rawDescGZIP(), []int{5}
}

func (x *ReporteCaptura) GetCazarrecompensaId() string {
	if x != nil {
		return x.CazarrecompensaId
	}
	return ""
}

func (x *ReporteCaptura) GetPirataId() string {
	if x != nil {
		return x.PirataId
	}
	return ""
}

type ConfirmacionCaptura struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmacionCaptura) Reset() {
	*x = ConfirmacionCaptura{}
	mi := &file_piratas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmacionCaptura) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmacionCaptura) ProtoMessage() {}

func (x *ConfirmacionCaptura) ProtoReflect() protoreflect.Message {
	mi := &file_piratas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmacionCaptura.ProtoReflect.Descriptor instead.
func (*ConfirmacionCaptura) Descriptor() ([]byte, []int) {
	return file_piratas_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmacionCaptura) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ConfirmacionCaptura) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_piratas_proto protoreflect.FileDescriptor

const file_piratas_proto_rawDesc = "" +
	"\n" +
	"\rpiratas.proto\x12\bonepiece\"\xae\x01\n" +
	"\x0fPirataCapturado\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x1e\n" +
	"\n" +
	"recompensa\x18\x03 \x01(\x05R\n" +
	"recompensa\x12/\n" +
	"\x13cazarrecompensas_id\x18\x04 \x01(\tR\x12cazarrecompensasId\x12\"\n" +
	"\fpeligrosidad\x18\x05 \x01(\tR\fpeligrosidad\"\xac\x01\n" +
	"\x0fResultadoCompra\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12\x16\n" +
	"\x06estado\x18\x02 \x01(\tR\x06estado\x12\x12\n" +
	"\x04caso\x18\x03 \x01(\tR\x04caso\x12!\n" +
	"\fmonto_pagado\x18\x04 \x01(\x05R\vmontoPagado\x12\x18\n" +
	"\amensaje\x18\x05 \x01(\tR\amensaje\x12\x18\n" +
	"\aentrega\x18\x06 \x01(\tR\aentrega\"?\n" +
	"\x0eSolicitudLista\x12-\n" +
	"\x12cazarrecompensa_id\x18\x01 \x01(\tR\x11cazarrecompensaId\"\x90\x01\n" +
	"\n" +
	"PirataInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x1e\n" +
	"\n" +
	"recompensa\x18\x03 \x01(\x04R\n" +
	"recompensa\x12\"\n" +
	"\fpeligrosidad\x18\x04 \x01(\tR\fpeligrosidad\x12\x16\n" +
	"\x06estado\x18\x05 \x01(\tR\x06estado\">\n" +
	"\fListaPiratas\x12.\n" +
	"\apiratas\x18\x01 \x03(\v2\x14.onepiece.PirataInfoR\apiratas\"\\\n" +
	"\x0eReporteCaptura\x12-\n" +
	"\x12cazarrecompensa_id\x18\x01 \x01(\tR\x11cazarrecompensaId\x12\x1b\n" +
	"\tpirata_id\x18\x02 \x01(\tR\bpirataId\"E\n" +
	"\x13ConfirmacionCaptura\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje2X\n" +
	"\x0fSubmundoService\x12E\n" +
	"\rComprarPirata\x12\x19.onepiece.PirataCapturado\x1a\x19.onepiece.ResultadoCompra2\xa6\x01\n" +
	"\x0fGobiernoService\x12G\n" +
	"\x13ObtenerListaPiratas\x12\x18.onepiece.SolicitudLista\x1a\x16.onepiece.ListaPiratas\x12J\n" +
	"\x0fReportarCaptura\x12\x18.onepiece.ReporteCaptura\x1a\x1d.onepiece.ConfirmacionCaptura2V\n" +
	"\rMarinaService\x12E\n" +
	"\rComprarPirata\x12\x19.onepiece.PirataCapturado\x1a\x19.onepiece.ResultadoCompraB\x13Z\x11grpc-server/protob\x06proto3"

var (
	file_piratas_proto_rawDescOnce sync.Once
	file_piratas_proto_rawDescData []byte
)

func file_piratas_proto_rawDescGZIP() []byte {
	file_piratas_proto_rawDescOnce.Do(func() {
		file_piratas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_piratas_proto_rawDesc), len(file_piratas_proto_rawDesc)))
	})
	return file_piratas_proto_rawDescData
}

var file_piratas_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_piratas_proto_goTypes = []any{
	(*PirataCapturado)(nil),     // 0: onepiece.PirataCapturado
	(*ResultadoCompra)(nil),     // 1: onepiece.ResultadoCompra
	(*SolicitudLista)(nil),      // 2: onepiece.SolicitudLista
	(*PirataInfo)(nil),          // 3: onepiece.PirataInfo
	(*ListaPiratas)(nil),        // 4: onepiece.ListaPiratas
	(*ReporteCaptura)(nil),      // 5: onepiece.ReporteCaptura
	(*ConfirmacionCaptura)(nil), // 6: onepiece.ConfirmacionCaptura
}
var file_piratas_proto_depIdxs = []int32{
	3, // 0: onepiece.ListaPiratas.piratas:type_name -> onepiece.PirataInfo
	0, // 1: onepiece.SubmundoService.ComprarPirata:input_type -> onepiece.PirataCapturado
	2, // 2: onepiece.GobiernoService.ObtenerListaPiratas:input_type -> onepiece.SolicitudLista
	5, // 3: onepiece.GobiernoService.ReportarCaptura:input_type -> onepiece.ReporteCaptura
	0, // 4: onepiece.MarinaService.ComprarPirata:input_type -> onepiece.PirataCapturado
	1, // 5: onepiece.SubmundoService.ComprarPirata:output_type -> onepiece.ResultadoCompra
	4, // 6: onepiece.GobiernoService.ObtenerListaPiratas:output_type -> onepiece.ListaPiratas
	6, // 7: onepiece.GobiernoService.ReportarCaptura:output_type -> onepiece.ConfirmacionCaptura
	1, // 8: onepiece.MarinaService.ComprarPirata:output_type -> onepiece.ResultadoCompra
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_piratas_proto_init() }
func file_piratas_proto_init() {
	if File_piratas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_piratas_proto_rawDesc), len(file_piratas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_piratas_proto_goTypes,
		DependencyIndexes: file_piratas_proto_depIdxs,
		MessageInfos:      file_piratas_proto_msgTypes,
	}.Build()
	File_piratas_proto = out.File
	file_piratas_proto_goTypes = nil
	file_piratas_proto_depIdxs = nil
}
