// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: piratas.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubmundoService_ComprarPirata_FullMethodName = "/submundo.SubmundoService/ComprarPirata"
)

// SubmundoServiceClient is the client API for SubmundoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio que ofrece el Submundo para COMPRAR piratas capturados
type SubmundoServiceClient interface {
	ComprarPirata(ctx context.Context, in *PirataCapturado, opts ...grpc.CallOption) (*ResultadoCompra, error)
}

type submundoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubmundoServiceClient(cc grpc.ClientConnInterface) SubmundoServiceClient {
	return &submundoServiceClient{cc}
}

func (c *submundoServiceClient) ComprarPirata(ctx context.Context, in *PirataCapturado, opts ...grpc.CallOption) (*ResultadoCompra, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultadoCompra)
	err := c.cc.Invoke(ctx, SubmundoService_ComprarPirata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubmundoServiceServer is the server API for SubmundoService service.
// All implementations must embed UnimplementedSubmundoServiceServer
// for forward compatibility.
//
// Servicio que ofrece el Submundo para COMPRAR piratas capturados
type SubmundoServiceServer interface {
	ComprarPirata(context.Context, *PirataCapturado) (*ResultadoCompra, error)
	mustEmbedUnimplementedSubmundoServiceServer()
}

// UnimplementedSubmundoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubmundoServiceServer struct{}

func (UnimplementedSubmundoServiceServer) ComprarPirata(context.Context, *PirataCapturado) (*ResultadoCompra, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComprarPirata not implemented")
}
func (UnimplementedSubmundoServiceServer) mustEmbedUnimplementedSubmundoServiceServer() {}
func (UnimplementedSubmundoServiceServer) testEmbeddedByValue()                         {}

// UnsafeSubmundoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubmundoServiceServer will
// result in compilation errors.
type UnsafeSubmundoServiceServer interface {
	mustEmbedUnimplementedSubmundoServiceServer()
}

func RegisterSubmundoServiceServer(s grpc.ServiceRegistrar, srv SubmundoServiceServer) {
	// If the following call pancis, it indicates UnimplementedSubmundoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubmundoService_ServiceDesc, srv)
}

func _SubmundoService_ComprarPirata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PirataCapturado)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmundoServiceServer).ComprarPirata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubmundoService_ComprarPirata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmundoServiceServer).ComprarPirata(ctx, req.(*PirataCapturado))
	}
	return interceptor(ctx, in, info, handler)
}

// SubmundoService_ServiceDesc is the grpc.ServiceDesc for SubmundoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubmundoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "submundo.SubmundoService",
	HandlerType: (*SubmundoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComprarPirata",
			Handler:    _SubmundoService_ComprarPirata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "piratas.proto",
}
