// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: piratas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Información del pirata ofrecido por el cazarrecompensas
type PirataCapturado struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre             string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Recompensa         int32                  `protobuf:"varint,3,opt,name=recompensa,proto3" json:"recompensa,omitempty"`
	CazarrecompensasId string                 `protobuf:"bytes,4,opt,name=cazarrecompensas_id,json=cazarrecompensasId,proto3" json:"cazarrecompensas_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PirataCapturado) Reset() {
	*x = PirataCapturado{}
	mi := &file_piratas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PirataCapturado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PirataCapturado) ProtoMessage() {}

func (x *PirataCapturado) ProtoReflect() protoreflect.Message {
	mi := &file_piratas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PirataCapturado.ProtoReflect.Descriptor instead.
func (*PirataCapturado) Descriptor() ([]byte, []int) {
	return file_piratas_proto_rawDescGZIP(), []int{0}
}

func (x *PirataCapturado) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PirataCapturado) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *PirataCapturado) GetRecompensa() int32 {
	if x != nil {
		return x.Recompensa
	}
	return 0
}

func (x *PirataCapturado) GetCazarrecompensasId() string {
	if x != nil {
		return x.CazarrecompensasId
	}
	return ""
}

// Resultado de la compra
type ResultadoCompra struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	MontoPagado   int32                  `protobuf:"varint,3,opt,name=monto_pagado,json=montoPagado,proto3" json:"monto_pagado,omitempty"`
	FueFraude     bool                   `protobuf:"varint,4,opt,name=fue_fraude,json=fueFraude,proto3" json:"fue_fraude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultadoCompra) Reset() {
	*x = ResultadoCompra{}
	mi := &file_piratas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultadoCompra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultadoCompra) ProtoMessage() {}

func (x *ResultadoCompra) ProtoReflect() protoreflect.Message {
	mi := &file_piratas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultadoCompra.ProtoReflect.Descriptor instead.
func (*ResultadoCompra) Descriptor() ([]byte, []int) {
	return file_piratas_proto_rawDescGZIP(), []int{1}
}

func (x *ResultadoCompra) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ResultadoCompra) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ResultadoCompra) GetMontoPagado() int32 {
	if x != nil {
		return x.MontoPagado
	}
	return 0
}

func (x *ResultadoCompra) GetFueFraude() bool {
	if x != nil {
		return x.FueFraude
	}
	return false
}

var File_piratas_proto protoreflect.FileDescriptor

const file_piratas_proto_rawDesc = "" +
	"\n" +
	"\rpiratas.proto\x12\bsubmundo\"\x8a\x01\n" +
	"\x0fPirataCapturado\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x1e\n" +
	"\n" +
	"recompensa\x18\x03 \x01(\x05R\n" +
	"recompensa\x12/\n" +
	"\x13cazarrecompensas_id\x18\x04 \x01(\tR\x12cazarrecompensasId\"\x83\x01\n" +
	"\x0fResultadoCompra\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12!\n" +
	"\fmonto_pagado\x18\x03 \x01(\x05R\vmontoPagado\x12\x1d\n" +
	"\n" +
	"fue_fraude\x18\x04 \x01(\bR\tfueFraude2X\n" +
	"\x0fSubmundoService\x12E\n" +
	"\rComprarPirata\x12\x19.submundo.PirataCapturado\x1a\x19.submundo.ResultadoCompraB\x13Z\x11grpc-server/protob\x06proto3"

var (
	file_piratas_proto_rawDescOnce sync.Once
	file_piratas_proto_rawDescData []byte
)

func file_piratas_proto_rawDescGZIP() []byte {
	file_piratas_proto_rawDescOnce.Do(func() {
		file_piratas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_piratas_proto_rawDesc), len(file_piratas_proto_rawDesc)))
	})
	return file_piratas_proto_rawDescData
}

var file_piratas_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_piratas_proto_goTypes = []any{
	(*PirataCapturado)(nil), // 0: submundo.PirataCapturado
	(*ResultadoCompra)(nil), // 1: submundo.ResultadoCompra
}
var file_piratas_proto_depIdxs = []int32{
	0, // 0: submundo.SubmundoService.ComprarPirata:input_type -> submundo.PirataCapturado
	1, // 1: submundo.SubmundoService.ComprarPirata:output_type -> submundo.ResultadoCompra
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_piratas_proto_init() }
func file_piratas_proto_init() {
	if File_piratas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_piratas_proto_rawDesc), len(file_piratas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_piratas_proto_goTypes,
		DependencyIndexes: file_piratas_proto_depIdxs,
		MessageInfos:      file_piratas_proto_msgTypes,
	}.Build()
	File_piratas_proto = out.File
	file_piratas_proto_goTypes = nil
	file_piratas_proto_depIdxs = nil
}
