// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: piratas.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GobiernoService_ObtenerListaPiratas_FullMethodName = "/onepiece.GobiernoService/ObtenerListaPiratas"
	GobiernoService_ReportarCaptura_FullMethodName     = "/onepiece.GobiernoService/ReportarCaptura"
)

// GobiernoServiceClient is the client API for GobiernoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Servicio para consultar y reportar capturas
type GobiernoServiceClient interface {
	ObtenerListaPiratas(ctx context.Context, in *SolicitudLista, opts ...grpc.CallOption) (*ListaPiratas, error)
	ReportarCaptura(ctx context.Context, in *ReporteCaptura, opts ...grpc.CallOption) (*ConfirmacionCaptura, error)
}

type gobiernoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGobiernoServiceClient(cc grpc.ClientConnInterface) GobiernoServiceClient {
	return &gobiernoServiceClient{cc}
}

func (c *gobiernoServiceClient) ObtenerListaPiratas(ctx context.Context, in *SolicitudLista, opts ...grpc.CallOption) (*ListaPiratas, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaPiratas)
	err := c.cc.Invoke(ctx, GobiernoService_ObtenerListaPiratas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gobiernoServiceClient) ReportarCaptura(ctx context.Context, in *ReporteCaptura, opts ...grpc.CallOption) (*ConfirmacionCaptura, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmacionCaptura)
	err := c.cc.Invoke(ctx, GobiernoService_ReportarCaptura_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GobiernoServiceServer is the server API for GobiernoService service.
// All implementations must embed UnimplementedGobiernoServiceServer
// for forward compatibility.
//
// Servicio para consultar y reportar capturas
type GobiernoServiceServer interface {
	ObtenerListaPiratas(context.Context, *SolicitudLista) (*ListaPiratas, error)
	ReportarCaptura(context.Context, *ReporteCaptura) (*ConfirmacionCaptura, error)
	mustEmbedUnimplementedGobiernoServiceServer()
}

// UnimplementedGobiernoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGobiernoServiceServer struct{}

func (UnimplementedGobiernoServiceServer) ObtenerListaPiratas(context.Context, *SolicitudLista) (*ListaPiratas, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerListaPiratas not implemented")
}
func (UnimplementedGobiernoServiceServer) ReportarCaptura(context.Context, *ReporteCaptura) (*ConfirmacionCaptura, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportarCaptura not implemented")
}
func (UnimplementedGobiernoServiceServer) mustEmbedUnimplementedGobiernoServiceServer() {}
func (UnimplementedGobiernoServiceServer) testEmbeddedByValue()                         {}

// UnsafeGobiernoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GobiernoServiceServer will
// result in compilation errors.
type UnsafeGobiernoServiceServer interface {
	mustEmbedUnimplementedGobiernoServiceServer()
}

func RegisterGobiernoServiceServer(s grpc.ServiceRegistrar, srv GobiernoServiceServer) {
	// If the following call pancis, it indicates UnimplementedGobiernoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GobiernoService_ServiceDesc, srv)
}

func _GobiernoService_ObtenerListaPiratas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudLista)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GobiernoServiceServer).ObtenerListaPiratas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GobiernoService_ObtenerListaPiratas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GobiernoServiceServer).ObtenerListaPiratas(ctx, req.(*SolicitudLista))
	}
	return interceptor(ctx, in, info, handler)
}

func _GobiernoService_ReportarCaptura_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReporteCaptura)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GobiernoServiceServer).ReportarCaptura(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GobiernoService_ReportarCaptura_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GobiernoServiceServer).ReportarCaptura(ctx, req.(*ReporteCaptura))
	}
	return interceptor(ctx, in, info, handler)
}

// GobiernoService_ServiceDesc is the grpc.ServiceDesc for GobiernoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GobiernoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onepiece.GobiernoService",
	HandlerType: (*GobiernoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ObtenerListaPiratas",
			Handler:    _GobiernoService_ObtenerListaPiratas_Handler,
		},
		{
			MethodName: "ReportarCaptura",
			Handler:    _GobiernoService_ReportarCaptura_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "piratas.proto",
}
